### ISSUE TITLE
Adjusting the quantity of an item in the cart

### ISSUE THREAD

**Issue by mikedao** [martensonbj/little_shop#13]
Background: My cart has an item in it
      As a visitor
      When I visit "/cart"
      Then I should see my item with a quantity of 1
      And when I increase the quantity
      Then my current page should be '/cart'
      And that item's quantity should reflect the increase
      And the subtotal for that item should increase
      And the total for the cart should match that increase
      And when I decrease the quantity
      Then my current page should be '/cart'
      And that item's quantity should reflect the decrease
      And the subtotal for that item should decrease
      And the total for the cart should match that decrease

**Comment by Tman22** [comment]
[WIP]
