### ISSUE TITLE
Viewing a past order Part Deux

### ISSUE THREAD

**Issue by mikedao** [martensonbj/little_shop#16]
Background: An existing user that has one previous order
      As an authenticated user
      When I visit "/orders"
      Then I should see my past order
      And I should see a link to view that order
      And when I click that link
      Then I should see each item that was order with the quantity and line-item subtotals
      And I should see links to each item's show page
      And I should see the current status of the order (ordered, paid, cancelled, completed)
      And I should see the total price for the order
      And I should see the date/time that the order was submitted
      If the order was completed or cancelled
      Then I should see a timestamp when the action took place
      And if any of the items in the order were retired from the menu
      Then they should still be able to access the item page
      But they should not be able to add the item to their cart

**Comment by ToniRib** [comment]
@mikedao why are we doing this part? It seems like a whole different user story to us, that would make more sense after we know how these actions actually take place and what the work flow is. We would rather do this with whatever the next user story is.
```
  If the order was completed or cancelled
      Then I should see a timestamp when the action took place
      And if any of the items in the order were retired from the menu
      Then they should still be able to access the item page
      But they should not be able to add the item to their cart
```

**Comment by martensonbj** [comment]
This was added to another waffle card and the pull request was merged in...not sure why the cards double up sometimes. Moving to done.
