### ISSUE TITLE
Admin Viewing items

### ISSUE THREAD

**Issue by mikedao** [martensonbj/little_shop#77]
As an Admin
When I visit "/admin/dashboard"
Then I should see a link for viewing all items
And when I click that link
Then my current path should be "/admin/items"
Then I should see a table with all items (active and inactive)
And each item should have:
  - A thumbnail of the image
  - Title that links to the item
  - Description
  - Status
  - Actions (Edit)

**Comment by Tman22** [comment]
Briefly touched on this while creating admins ability to edit(78). The pull request 78, has most of this functionality.
